DEPENDS += "maven-bin-native openjdk-bin-native"

MAVEN_REPO_URL ?= "https://repo1.maven.org/maven2"

python do_update_maven_deps() {
    import os
    import hashlib
    import subprocess
    import sys

    staging_dir_native = d.getVar("STAGING_DIR_NATIVE")
    dl_dir = d.getVar("DL_DIR")
    libdir = d.getVar("libdir")

    JAVA_HOME = f"{staging_dir_native}/{libdir}/jvm"
    M2_HOME = f"{staging_dir_native}/{libdir}/maven"
    MAVEN_HOME = f"{staging_dir_native}/{libdir}/maven"
    MAVEN_REPO_DIR = f"{dl_dir}/maven-repo"
    mvn = f"{staging_dir_native}/usr/lib/maven/bin/mvn"

    s_dir = d.getVar("S")
    bpn = d.getVar("BPN")
    workdir = d.getVar("WORKDIR")
    temp_m2 = os.path.join(workdir, "temp-m2-repo")
    inc_filename = os.path.join(d.getVar("THISDIR"), f"{bpn}-deps.inc")
    repo_url = d.getVar("MAVEN_REPO_URL").rstrip('/')

    os.environ["JAVA_HOME"] = JAVA_HOME
    os.environ["M2_HOME"] = M2_HOME
    os.environ["MAVEN_HOME"] = MAVEN_HOME
    os.environ["MAVEN_REPO_DIR"] = MAVEN_REPO_DIR
    cmd = [
        mvn,
        "org.apache.maven.plugins:maven-dependency-plugin:3.11.0:go-offline",
        f"-Dmaven.repo.local={temp_m2}",
        "-f", s_dir
    ]
    bb.note(f"Running Maven dependency resolution: {' '.join(cmd)}")
    subprocess.check_call(cmd)

    src_uris = []
    checksums = []

    for root, _, files in os.walk(temp_m2):
        for file in files:
            # Maven creates several local files that don't need to be checked.
            if file.endswith(('.repositories', '_remote.repositories', '.lastUpdated', '.sha1', '.md5')):
                continue

            full_path = os.path.join(root, file)
            rel_path = os.path.relpath(full_path, temp_m2)
            rel_dir = os.path.dirname(rel_path)

            # Generate unique BitBake parameter name
            name_key = rel_path.replace('/', '_').replace('.', '_').replace('-', '_')

            hasher = hashlib.sha256()
            with open(full_path, 'rb') as f:
                while chunk := f.read(65536):
                    hasher.update(chunk)
            sha256 = hasher.hexdigest()

            remote_url = f"{repo_url}/{rel_path}"

            src_uris.append(
                f"    {remote_url};name={name_key};downloadfilename=maven-repo/{rel_path};subdir=m2-repo/{rel_dir} \\"
            )
            checksums.append(f"SRC_URI[{name_key}.sha256sum] = \"{sha256}\"")

    with open(inc_filename, 'w') as f:
        f.write("# Auto-generated by maven_update_deps.bbclass; DO NOT EDIT\n\n")
        f.write("SRC_URI += \" \\\n")
        f.write(f"\n{.join(src_uris)}\n\"\n\n")
        f.write(f"\n{.join(checksums)}\n")

    bb.plain(f"Successfully generated dependency include file: {inc_filename}")
}
addtask do_update_maven_deps after do_patch
do_update_maven_deps[network] = "1"
do_update_maven_deps[nostamp] = "1"
do_update_maven_deps[doc] = "pre-download and create a deps.inc file. Much like cargo."
RECIPE_UPGRADE_EXTRA_TASKS += "do_update_maven_deps"
